#!/usr/bin/env node
/**
 * UPSERT JSON из src/data в D1 (remote или local).
 *   npm run db:seed
 *   npm run db:seed -- --local
 */
import fs from 'fs'
import path from 'path'
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')
const DB_NAME = process.env.D1_DATABASE_NAME?.trim() || 'csutility-editor'
const local = process.argv.includes('--local')

const FILES = [
  { key: 'custom_lineups', file: 'src/data/custom-lineups.json' },
  { key: 'position_overrides', file: 'src/data/position-overrides.json' },
  { key: 'position_catalog_extensions', file: 'src/data/position-catalog-extensions.json' },
  { key: 'position_zones', file: 'src/data/position-zones.json' },
]

const lines = ['-- generated by d1-seed.mjs']
for (const { key, file } of FILES) {
  const abs = path.join(root, file)
  if (!fs.existsSync(abs)) {
    console.warn('Пропуск (нет файла):', file)
    continue
  }
  const payload = fs.readFileSync(abs, 'utf8').trim()
  JSON.parse(payload)
  const escaped = payload.replace(/'/g, "''")
  lines.push(
    `INSERT INTO editor_content (key, payload, updated_at) VALUES ('${key}', '${escaped}', unixepoch())`,
    `ON CONFLICT(key) DO UPDATE SET payload = excluded.payload, updated_at = unixepoch();`,
  )
}

const sqlPath = path.join(root, '.tmp-d1-seed.sql')
fs.writeFileSync(sqlPath, lines.join('\n'), 'utf8')

const args = ['wrangler', 'd1', 'execute', DB_NAME, '--file', sqlPath]
if (local) args.push('--local')
else args.push('--remote')

console.log('D1 seed:', local ? 'local' : 'remote', DB_NAME)
const r = spawnSync('npx', args, { cwd: root, stdio: 'inherit', shell: true })
fs.unlinkSync(sqlPath)
process.exit(r.status ?? 1)
